apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 02_ElasticSearch_Service.yaml
  - 03_ElasticSearch_StatefulSet.yaml
  - 04_Fluentd_ConfigMap.yaml
  - 05_Fluend_DaemonSet.yaml
  - 06_Kibana_Deployment.yaml
  - 07_Kibana_Service.yaml
  - 08_kibana_ingress.yaml